Repository rdohms/phpunit-arraysubset-asserts, pull requests merged in 2020-10, with the labels that each got.

#8 Add variable name for ease of use
  README.md
Labels: Documentation

#22 Configure dependabot
  .github/dependabot.yml
Labels: CI

#20 Replace Travis with Github Actions
  .github/workflows/check-cs.yml
  .github/workflows/run-tests.yml
  .travis.yml
Labels: CI, hacktoberfest-accepted

#25 Include ArrayAccessible class
  composer.json
  src/ArrayAccessible.php
  tests/Unit/Constraint/ArraySubsetTest.php
Labels: Bug

#17 Add support for PHP 8
  composer.json
Labels: Feature

#28 Run CS on PR
  .github/workflows/check-cs.yml
  src/ArrayAccessible.php
  tests/Unit/Constraint/ArraySubsetTest.php
Labels: CI, Refactoring
