Repository rdohms/phpunit-arraysubset-asserts, pull requests merged in 2021-04, with the labels that each got.

#44 PHP8 / Composer 2 Compatibility
  .github/workflows/run-tests.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  src/ArrayAccessible.php
  src/ArraySubsetAsserts.php
  src/Constraint/ArraySubset.php
  tests/Unit/Constraint/ArraySubsetTest.php
Labels: Refactoring

#36 Add support for use with PHPUnit Phar
  src/Constraint/ArraySubset.php
Labels: Feature

#37 Add .gitattributes file
  .gitattributes
Labels: Refactoring

#45 Composer: coding standard is a dev requirement
  composer.json
  composer.lock
Labels: Refactoring

#47 README: clarify code examples
  README.md
Labels: Documentation
